### ISSUE TITLE
Wrong task names with Capistrano 3.x

### ISSUE THREAD

**Issue by nestorw** [adamcooke/procodile-capistrano#1]
The task names have changed in Capistrano 3.x.
I'm getting this after running `cap -T` on Capistrano 3.6.1

```
cap aborted!
Don't know how to build task 'deploy:start' (see --tasks)
```

http://capistranorb.com/documentation/getting-started/flow/

Procodile commands should also probably be run `after 'deploy:finished'`.
That way if anything fails earlier in the deploy, the currently running processes won't be affected.

Procodile is great! It's way easier to set up than god/bluepill.
Thanks!

**Comment by adamcooke** [comment]
I'm actually still a Cap2 user and I didn't test the capistrano 3 bits so thanks for pointing this out. I've changed the callbacks to run the restart after `deploy:finished`. Do feel free to submit a pull request or let me know if anything else needs adjusting here.
