### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jpalumickas** [adamcooke/procodile-capistrano#3]
Hello,

Can you make a new release of this gem, to have this https://github.com/adamcooke/procodile-capistrano/commit/60ff6fec360e9276686ee6e27656e5661918590e fix?

Cheers!

**Comment by adamcooke** [comment]
Done (1.0.2)! 😄 Thanks for the reminder.

**Comment by jpalumickas** [comment]
Thanks! 👍
